export default {
  CREATE_PROJECT: 'CREATE_PROJECT',
  UPDATE_PROJECT: 'UPDATE_PROJECT',
  DELETE_PROJECT: 'DELETE_PROJECT',
  CREATE_PROJECT_HOUSEHOLD_ARTICLE: 'CREATE_PROJECT_HOUSEHOLD_ARTICLE',
  UPDATE_PROJECT_HOUSEHOLD_ARTICLE: 'UPDATE_PROJECT_HOUSEHOLD_ARTICLE',
  DELETE_PROJECT_HOUSEHOLD_ARTICLE: 'DELETE_PROJECT_HOUSEHOLD_ARTICLE',
  SELECT_PROJECT: 'SELECT_PROJECT',
};
