export const CREATE_PROJECT = 'CREATE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const CREATE_PROJECT_HOUSEHOLD_ARTICLE = 'CREATE_PROJECT_HOUSEHOLD_ARTICLE';
export const UPDATE_PROJECT_HOUSEHOLD_ARTICLE = 'UPDATE_PROJECT_HOUSEHOLD_ARTICLE';
export const DELETE_PROJECT_HOUSEHOLD_ARTICLE = 'DELETE_PROJECT_HOUSEHOLD_ARTICLE';
export const SELECT_PROJECT = 'SELECT_PROJECT';
